# Generated by Django 2.2.3 on 2019-08-21 17:54

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name_plural': 'Directores',
                'ordering': ['-id'],
                'verbose_name': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.BooleanField(default=False, verbose_name='Portada')),
                ('nombre', models.CharField(max_length=225, verbose_name='Nombre')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='fotos/videos', verbose_name='Imagen')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('produccion', models.CharField(max_length=255, verbose_name='Producción')),
                ('duracion', models.CharField(max_length=20, verbose_name='Duración')),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('categoria', models.ManyToManyField(to='videoteca.Categoria', verbose_name='Categoría')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Director', verbose_name='Director')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais', verbose_name='País')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Tipo')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-id'],
                'verbose_name': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField(choices=[(1, 'Temporada 1'), (2, 'Temporada 2'), (3, 'Temporada 3'), (4, 'Temporada 4'), (5, 'Temporada 5')])),
                ('info_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Video')),
            ],
            options={
                'verbose_name_plural': 'Temporadas',
                'verbose_name': 'Temporada',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=225)),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='fotos/videos', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=225, verbose_name='Título')),
                ('sinopsis', models.TextField(max_length=200, verbose_name='Sinopsis')),
                ('duracion', models.CharField(max_length=20, verbose_name='Duración')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio_temporada', to='videoteca.Temporada')),
            ],
            options={
                'verbose_name_plural': 'Episodios',
                'verbose_name': 'Episodio',
            },
        ),
    ]
