# Generated by Django 2.2.3 on 2019-07-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('sinopsis', models.CharField(max_length=225)),
                ('fecha', models.DateField()),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Categorias')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Directores')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Tipos')),
            ],
        ),
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=225)),
                ('sinopsis', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('info_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Videos')),
            ],
        ),
    ]
