# Generated by Django 2.2.3 on 2019-08-30 17:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sinopsis',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción'),
        ),
    ]
