# Generated by Django 2.2.3 on 2019-08-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Temporada'),
        ),
    ]
