# Generated by Django 2.2.3 on 2019-07-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=225)),
                ('sinopsis', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField(choices=[(1, 'Temporada 1'), (2, 'Temporada 2'), (3, 'Temporada 3'), (4, 'Temporada 4'), (5, 'Temporada 5')])),
                ('info_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Videos')),
            ],
        ),
        migrations.DeleteModel(
            name='Enlaces',
        ),
        migrations.AddField(
            model_name='episodios',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio_temporada', to='videoteca.Temporadas'),
        ),
    ]
