# Generated by Django 2.2.3 on 2019-07-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['-id'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='episodio',
            options={'verbose_name': 'Episodio', 'verbose_name_plural': 'Episodios'},
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
