# Generated by Django 2.2.3 on 2019-08-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='duracion',
            field=models.TimeField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='sinopsis',
            field=models.CharField(max_length=225, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='titulo',
            field=models.CharField(max_length=225, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ManyToManyField(to='videoteca.Categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='video',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Director', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.TextField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(max_length=225, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='video',
            name='produccion',
            field=models.CharField(max_length=255, verbose_name='Producción'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sinopsis',
            field=models.TextField(verbose_name='Sinopsis'),
        ),
    ]
