# Generated by Django 2.2.3 on 2019-07-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_auto_20190709_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
