# Generated by Django 2.2.3 on 2019-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_auto_20190715_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
