# Generated by Django 2.2.3 on 2019-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_auto_20190808_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.CharField(max_length=20, verbose_name='Duración'),
        ),
    ]
