# Generated by Django 2.2.3 on 2019-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0003_auto_20190715_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.TimeField(),
        ),
    ]
