# Generated by Django 2.2.3 on 2019-07-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0003_videos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodios',
            name='link',
            field=models.URLField(max_length=225),
        ),
    ]
