# Generated by Django 2.2.3 on 2019-08-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0004_auto_20190808_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='slug',
        ),
    ]
