# Generated by Django 2.2.3 on 2019-07-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0004_auto_20190715_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='live',
        ),
    ]
