# Generated by Django 2.2.3 on 2019-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0005_remove_video_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='duracion',
            field=models.TimeField(default='00:00:00:00'),
            preserve_default=False,
        ),
    ]
