# Generated by Django 2.2.3 on 2019-07-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='HoraProgramacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion')),
            ],
            options={
                'verbose_name': 'Hora Programación',
                'verbose_name_plural': 'Horas de programacion',
            },
        ),
    ]
