# Generated by Django 2.2.3 on 2019-08-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('link', models.URLField(blank=True, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='HoraProgramacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('categoria_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Categoria', verbose_name='Categoría')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion')),
            ],
            options={
                'verbose_name': 'Hora Programación',
                'verbose_name_plural': 'Horas de programacion',
            },
        ),
    ]
