# Generated by Django 2.2.3 on 2019-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
