# Generated by Django 2.2.3 on 2019-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_auto_20190715_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='hora',
            field=models.TimeField(),
        ),
    ]
