# Generated by Django 2.2.3 on 2019-07-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_auto_20190715_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacion',
            options={'verbose_name': 'Programación', 'verbose_name_plural': 'Programaciones'},
        ),
    ]
