# Generated by Django 2.2.3 on 2019-07-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0005_auto_20190717_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaprogramacion',
            options={'verbose_name': 'Hora Programación', 'verbose_name_plural': 'Horas de programacion'},
        ),
    ]
