# Generated by Django 2.2.3 on 2019-07-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0006_auto_20190717_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacion',
            options={'verbose_name': 'Programación', 'verbose_name_plural': 'Programaciones'},
        ),
    ]
