# Generated by Django 2.2.3 on 2019-07-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('descripcion', models.TextField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/noticias')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documento/biblioteca')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Categoria')),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Biblioteca',
            },
        ),
    ]
