# Generated by Django 2.2.3 on 2019-07-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='archivo',
            field=models.FileField(default=' ', upload_to='documento/biblioteca'),
            preserve_default=False,
        ),
    ]
