# Generated by Django 2.2.3 on 2019-08-12 19:29

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(upload_to='fotos/biblioteca', verbose_name='Imagen'),
        ),
    ]
