# Generated by Django 2.2.3 on 2019-08-21 17:54

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Clasificaciones',
                'verbose_name': 'Clasificacion',
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Noticia'), (2, 'Reportaje')])),
                ('ultimo_momento', models.BooleanField(default=False)),
                ('portada', models.BooleanField(default=False, verbose_name='Portada')),
                ('titulo', models.CharField(max_length=225)),
                ('fecha', models.DateField()),
                ('banner', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='banner/noticias', verbose_name='Banner')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='fotos/noticias', verbose_name='Imagen')),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias/Reportajes',
                'verbose_name': 'Noticia/Reportaje',
            },
        ),
    ]
