# Generated by Django 2.2.3 on 2019-08-30 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20190827_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción'),
        ),
    ]
