# Generated by Django 2.2.3 on 2019-07-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20190715_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='descripcion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Tipo'),
        ),
    ]
