# Generated by Django 2.2.3 on 2019-08-12 19:29

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20190808_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(upload_to='fotos/noticias', verbose_name='Imagen'),
        ),
    ]
