# Generated by Django 2.2.3 on 2019-07-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20190715_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion',
            name='categoria',
        ),
    ]
