# Generated by Django 2.2.3 on 2019-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20190812_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='portada',
            field=models.BooleanField(default=False, verbose_name='Portada'),
        ),
    ]
