# Generated by Django 2.2.3 on 2019-08-19 16:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190819_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
