# Generated by Django 2.2.3 on 2019-08-19 18:00

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20190819_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='banner/noticias', verbose_name='Banner'),
        ),
    ]
